### ISSUE TITLE
Glorious Vanity Jewel's "Ritual of Flesh" nodes show inflated life regen numbers

### ISSUE THREAD

**Issue by nikhilm05** [Vilsol/timeless-jewels#12]
When selecting Glorious Vanity and any conqueror, the "Ritual of Flesh" nodes appear to have "Regenerate #% of life per second" nodes that are way outside of the possible values. For example:

![image](https://github.com/Vilsol/timeless-jewels/assets/37055755/7b7eac2d-97a0-4f55-a470-a12b824d65ab)

(The shown selection is seed 486)

This problem persists throughout the few jewel slots I looked at. The values range from 50% to almost 80% life regen per second, while as per poewiki.net, Ritual of Flesh should only provide the following:

> (6-10)% increased maximum Life
> Regenerate (0.7-1.2)% of Life per second

**Comment by Vilsol** [comment]
Should be fixed now
