### ISSUE TITLE
[Issue] Search Defaults to Sentinel

### ISSUE THREAD

**Issue by livejamie** [Vilsol/timeless-jewels#18]
It's currently Ancestor league.

![image](https://github.com/Vilsol/timeless-jewels/assets/49513/f77ed594-da51-447d-b2fc-81f5fafd3e0f)

Clicking this button takes you to a broken Sentinel league search.

**Comment by NicPucacco** [comment]
Now its Affliction, still defaults to Sentinel.
https://github.com/Vilsol/timeless-jewels/blob/main/frontend/src/lib/skill_tree.ts#L460

**Comment by Vilsol** [comment]
Fixed
