### ISSUE TITLE
Trade Button Includes Results for all Conquerers

### ISSUE THREAD

**Issue by DFXLuna** [Vilsol/timeless-jewels#5]
I set up the following search, selecting a particular conqueror and relevant stats: 
![image](https://user-images.githubusercontent.com/11394152/215211434-71d8edce-b0d1-4c63-a1f7-7820c2214aeb.png)

I found a great jewel and hit the trade button. Note that the tree display shows the keystone linked to my chosen conqueror (Doryani = Corrupted Soul):
![image](https://user-images.githubusercontent.com/11394152/215212116-e58deb13-93bd-4c0c-9d34-1ca6449cb8bc.png)

However, the trade link on the seed sends me to the trade page for that seed but with all conquerors selected:
![image](https://user-images.githubusercontent.com/11394152/215212333-75af821d-9529-4238-9b7b-1c16f8200b24.png)

It should probably includ only the selected conqueror so that people who are a little dumb(like me) buy the correct the jewel :)

The trade button at the top of the seed selection only shows trades for the correct conqueror:
![image](https://user-images.githubusercontent.com/11394152/215213096-38ea5b99-ffe5-46be-aff2-dc7e3b35ce6b.png)

Thanks!

**Comment by gkrastev96** [comment]
Problem still persists unfortunately.

**Comment by DFXLuna** [comment]
Looks fixed as of yesterday by #13 

Thanks!
