### ISSUE TITLE
need update!

### ISSUE THREAD

**Issue by icetooth-sketch** [Vilsol/timeless-jewels#6]

**Comment by zrisher** [comment]
While this ticket doesn't quite describe the issue the user faced, I believe they meant that the current version of this tool is producing different results for the passive tree than the current version of PoE. I personally noticed this after finding a particular jewel with this tool, then purchasing it in game, only to realize different results.

**Comment by Vilsol** [comment]
Going to update it later tonight

**Comment by zrisher** [comment]
Great to hear, appreciate your work on this tool.

**Comment by icetooth-sketch** [comment]
> Going to update it later tonight

gigachad

**Comment by Vilsol** [comment]
Updated
