### ISSUE TITLE
Wrong value displayed

### ISSUE THREAD

**Issue by fzabnicki** [Vilsol/timeless-jewels#8]
Hello, 
I've been looking for a timeless-jewel that is placed in spot near Supreme Ego. Acording to the site https://vilsol.github.io/ jewel: Elegant Hubris (Caspiro) 15300 should have 3 rarity nodes. On Balistics and Dire torment it's ok but should be another one on Master Sapper place (previously True Strike spot -> it is now further and circle don't reach it). However in game there is 12% non-curse aura effect. I guess problem happened because passive tree changed a bit.

**Comment by Vilsol** [comment]
I have just updated the tool to the new tree, can you please verify that the values are valid on the site?

**Comment by fzabnicki** [comment]
For my example now working correctly. I guess it will work fine right now. Thanks!
