### ISSUE TITLE
Some mods are not available for search

### ISSUE THREAD

**Issue by ArcaneHunter** [Vilsol/timeless-jewels#9]
When using the tool https://vilsol.github.io/timeless-jewels , a couple mods were not available for search.

Ex: to Cold Resistance, to Chaos Resistance, increased Movement Speed, increased Area of Effect(those are mods I check because they were important for my build).

Additional information: I cloned the repo to try to check if I could fix since only a couple are missing, but I do not know go but this might help debugging. 

File alternate_passive_additions.json.gz has no mistakes as far as I checked. 

I don't know what "possible_stats.json.gz" is doing but it has all the keys that are used in "alternate_passive_additions.json.gz"(even from the mods that are missing from search).

File "stat_descriptions.json.gz" has "list":[{"string":"{0:+d}% to Fire Resistance"}]} and "list":[{"string":"{0:+d}% to Lightning Resistance"}]} but is missing "list":[{"string":"{0:+d}% to Chaos Resistance"}]} and "list":[{"string":"{0:+d}% to Cold Resistance"}]}. I believe the mods that can't be searched are missing from this file.

I was gonna try to fix myself by running https://github.com/Vilsol/go-pob-data and making a text-text comparison with "stat_descriptions.json.gz" but when I tried hosting a copy of this repo(https://github.com/Vilsol/timeless-jewels) myself I got a blank page in github.io. I hope this shorten the work you need to do to fix it.

**Comment by Vilsol** [comment]
Should be fixed in latest release. It was just a translation file bug
